# Authentication
password = "Stockee123"

# API Configuration
MARKETAUX_API_KEY = "U5MbBySFtKY3YjVbVqObrUz5XYYx8VeJF12tcbUh"

# App Password
PASSWORD = "Stockee123"

# Google News API Key
GNEWS_API_KEY = "2c2ca85e5cb940c7bc91e25c561ded9c" 